AWSTemplateFormatVersion: 2010-09-09
# This can only be deployed once per account.

Resources:

  GitHubOIDC:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938FD4D98BAB03FAADB97B34396831E3780AEA1

Outputs:

  GitHubOIDCArn:
    Value: !Ref GitHubOIDC

